In [564]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in c:\users\anups\anaconda3\envs\dev0\lib\site-packages (0.0.7)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\anups\anaconda3\envs\dev0\lib\site-packages (from ucimlrepo) (2024.2.2)
Requirement already satisfied: pandas>=1.0.0 in c:\users\anups\anaconda3\envs\dev0\lib\site-packages (from ucimlrepo) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in c:\users\anups\anaconda3\envs\dev0\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\anups\anaconda3\envs\dev0\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\anups\anaconda3\envs\dev0\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.21.5)
Requirement already satisfied: six>=1.5 in c:\users\anups\anaconda3\envs\dev0\lib\site-packages (from python-dateutil>=2.7.3->pandas>=1.0.0->ucimlrepo) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [565]:
import pandas as pd
import re
from collections import Counter

In [566]:
# Functions used to convert data

def yesNoBinaryConversion(input):    
    input.replace('yes', 1, inplace = True)
    input.replace('no', 0, inplace = True)
    
def weightReplacement(input):        
    replace_dicitonary = {r"\binsufficient": '0',
                        r"\bnormal": '1',
                       r"\boverweight": '2',
                        r"\bobesity": '3'}
    for index, value in enumerate(input):
        for key, item in replace_dicitonary.items():                 
            find_ = re.findall(key,value,re.I)
            if find_:
                input.replace(value, item, inplace=True)
                
def integerBuckets(input):
    for index, value in enumerate(input):
        if value > 3.5:
            input.replace(value, 3, inplace = True)
        elif value > 2.5:
            input.replace(value, 2, inplace = True)
        elif value > 1.5:
            input.replace(value, 1, inplace = True)
        else:
            input.replace(value, 0, inplace = True)

def categoricalBuckets(input):
    for index, value in enumerate(input):
        if value > 2.5:
            input.replace(value, 'Always', inplace = True)
        elif value > 1.5:
            input.replace(value, 'Frequently', inplace = True)
        else:
            input.replace(value, 'Sometimes', inplace = True)
            
def integer_3_Buckets(input):
    for index, value in enumerate(input):
        if value > 1.4:
            input.replace(value, 2, inplace = True)
        elif value > 0.7:
            input.replace(value, 1, inplace = True)
        else:
            input.replace(value, 0, inplace = True)

def ageRounding(input):
    for index, value in enumerate(input):
        input.replace(value, round(value, 0), inplace = True)
        
def h2oRounding(input):
    for index, value in enumerate(input):
        if value > 2.5:
            input.replace(value, 3, inplace = True)
        elif value > 1.5:
            input.replace(value, 2, inplace = True)
        else:
            input.replace(value, 1, inplace = True)
            
def activityRounding(input):
    for index, value in enumerate(input):
        if value > 2.4:
            input.replace(value, 3, inplace = True)
        elif value > 1.7:
            input.replace(value, 2, inplace = True)
        elif value > 0.7:
            input.replace(value, 1, inplace = True)
        else:
            input.replace(value, 0, inplace = True)

In [567]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition = fetch_ucirepo(id=544) 
  
# data (as pandas dataframes) 
feature_df = estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition.data.features 
y = estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition.data.targets

In [568]:
feature_df.nunique()

Gender                               2
Age                               1402
Height                            1574
Weight                            1525
family_history_with_overweight       2
FAVC                                 2
FCVC                               810
NCP                                635
CAEC                                 4
SMOKE                                2
CH2O                              1268
SCC                                  2
FAF                               1190
TUE                               1129
CALC                                 4
MTRANS                               5
dtype: int64

In [569]:
# View metadata and variable types
print(estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition.variables[['name', 'type', 'description']])

                              name         type  \
0                           Gender  Categorical
1                              Age   Continuous
2                           Height   Continuous
3                           Weight   Continuous
4   family_history_with_overweight       Binary
5                             FAVC       Binary
6                             FCVC      Integer
7                              NCP   Continuous
8                             CAEC  Categorical
9                            SMOKE       Binary
10                            CH2O   Continuous
11                             SCC       Binary
12                             FAF   Continuous
13                             TUE      Integer
14                            CALC  Categorical
15                          MTRANS  Categorical
16                      NObeyesdad  Categorical

                                          description
0                                                None
1                                                None
2                                                None
3                                                None
4   Has a family member suffered or suffers from o...
5            Do you eat high caloric food frequently?
6        Do you usually eat vegetables in your meals?
7              How many main meals do you have daily?
8                  Do you eat any food between meals?
9                                       Do you smoke?
10                 How much water do you drink daily?
11         Do you monitor the calories you eat daily?
12           How often do you have physical activity?
13  How much time do you use technological devices...
14                    How often do you drink alcohol?
15           Which transportation do you usually use?
16                                      Obesity level

# Processing Feature Data

In [570]:
# View df to see how data is stored. APply appropriate data conversions.
feature_df.head(50)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation
10,Male,26.0,1.85,105.0,yes,yes,3.0,3.0,Frequently,no,3.0,no,2.0,2.0,Sometimes,Public_Transportation
11,Female,21.0,1.72,80.0,yes,yes,2.0,3.0,Frequently,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation
12,Male,22.0,1.65,56.0,no,no,3.0,3.0,Sometimes,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation
13,Male,41.0,1.80,99.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Automobile
14,Male,23.0,1.77,60.0,yes,yes,3.0,1.0,Sometimes,no,1.0,no,1.0,1.0,Sometimes,Public_Transportation
15,Female,22.0,1.70,66.0,yes,no,3.0,3.0,Always,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation
16,Male,27.0,1.93,102.0,yes,yes,2.0,1.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation
17,Female,29.0,1.53,78.0,no,yes,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,no,Automobile
18,Female,30.0,1.71,82.0,yes,yes,3.0,4.0,Frequently,yes,1.0,no,0.0,0.0,no,Automobile
19,Female,23.0,1.65,70.0,yes,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation
20,Male,22.0,1.65,80.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,3.0,2.0,no,Walking
21,Female,52.0,1.69,87.0,yes,yes,3.0,1.0,Sometimes,yes,2.0,no,0.0,0.0,no,Automobile
22,Female,22.0,1.65,60.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Automobile
23,Female,22.0,1.60,82.0,yes,yes,1.0,1.0,Sometimes,no,2.0,no,0.0,2.0,Sometimes,Public_Transportation
24,Male,21.0,1.85,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,Sometimes,Public_Transportation
25,Male,20.0,1.60,50.0,yes,no,2.0,4.0,Frequently,yes,2.0,no,3.0,2.0,no,Public_Transportation
26,Male,21.0,1.70,65.0,yes,yes,2.0,1.0,Frequently,no,2.0,no,1.0,2.0,Always,Walking
27,Female,23.0,1.60,52.0,no,yes,2.0,4.0,Frequently,no,2.0,no,2.0,1.0,Sometimes,Automobile
28,Male,19.0,1.75,76.0,yes,yes,3.0,3.0,Sometimes,no,2.0,yes,3.0,1.0,Sometimes,Public_Transportation
29,Male,23.0,1.68,70.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,2.0,2.0,Frequently,Walking
30,Male,29.0,1.77,83.0,no,yes,1.0,4.0,Frequently,no,3.0,no,0.0,1.0,no,Motorbike
31,Female,31.0,1.58,68.0,yes,no,2.0,1.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation
32,Female,24.0,1.77,76.0,no,no,2.0,3.0,Sometimes,no,3.0,no,1.0,1.0,Sometimes,Walking
33,Male,39.0,1.79,90.0,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation
34,Male,22.0,1.65,62.0,no,yes,2.0,4.0,Frequently,no,2.0,no,2.0,0.0,Sometimes,Public_Transportation
35,Female,21.0,1.50,65.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,2.0,Sometimes,Public_Transportation
36,Female,22.0,1.56,49.0,no,yes,2.0,3.0,Sometimes,no,1.0,yes,2.0,0.0,no,Walking
37,Female,21.0,1.60,48.0,no,yes,2.0,3.0,Sometimes,no,1.0,no,1.0,0.0,Sometimes,Public_Transportation
38,Male,23.0,1.65,67.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Sometimes,Public_Transportation
39,Female,21.0,1.75,88.0,yes,yes,2.0,3.0,Sometimes,no,3.0,no,3.0,0.0,Sometimes,Public_Transportation
40,Female,21.0,1.67,75.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Public_Transportation
41,Male,23.0,1.68,60.0,no,no,2.0,4.0,Frequently,no,2.0,no,0.0,0.0,no,Walking
42,Female,21.0,1.66,64.0,yes,yes,1.0,3.0,Sometimes,no,1.0,no,0.0,0.0,no,Public_Transportation
43,Male,21.0,1.66,62.0,yes,yes,2.0,3.0,Sometimes,yes,2.0,no,1.0,1.0,Frequently,Public_Transportation
44,Male,21.0,1.81,80.0,no,no,1.0,3.0,no,no,2.0,no,2.0,0.0,no,Public_Transportation
45,Female,21.0,1.53,65.0,yes,no,2.0,3.0,Sometimes,no,1.0,no,0.0,1.0,no,Public_Transportation
46,Male,21.0,1.82,72.0,yes,yes,1.0,3.0,Frequently,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation
47,Male,21.0,1.75,72.0,yes,yes,1.0,3.0,Frequently,no,3.0,no,2.0,0.0,Sometimes,Public_Transportation
48,Female,20.0,1.66,60.0,yes,no,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Walking
49,Female,21.0,1.55,50.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation

In [571]:
# Replace binary value types with 1 for yes, 0 for no for all binary type columns

binary_list = []

for index, row in estimation_of_obesity_levels_based_on_eating_habits_and_physical_condition['variables'].iterrows():    
    
    
    if row['type'] == 'Binary':
        binary_list.append(row['name'])
        
for i in binary_list:
    yesNoBinaryConversion(feature_df[i])

c:\Users\anups\anaconda3\envs\dev0\lib\site-packages\pandas\core\generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [572]:
# Create a column which represents a known ratio of weight to height, i.e. BMI.
feature_df['BMI'] = round(feature_df['Weight'] / feature_df['Height']**2, 3)

In [573]:
# Round the age to an integer.
ageRounding(feature_df['Age'])

print(Counter(feature_df['Age']))

Counter({21.0: 236, 23.0: 218, 26.0: 213, 18.0: 212, 19.0: 169, 22.0: 163, 20.0: 150, 24.0: 95, 25.0: 82, 17.0: 69, 31.0: 62, 30.0: 53, 27.0: 43, 33.0: 37, 38.0: 34, 29.0: 33, 34.0: 29, 32.0: 26, 39.0: 25, 37.0: 24, 41.0: 20, 28.0: 20, 16.0: 20, 35.0: 19, 40.0: 19, 44.0: 6, 36.0: 6, 42.0: 6, 55.0: 5, 45.0: 3, 43.0: 3, 51.0: 2, 46.0: 2, 52.0: 1, 15.0: 1, 61.0: 1, 56.0: 1, 14.0: 1, 48.0: 1, 47.0: 1})

In [574]:
# Round off what water consumption onto 1.0, 2.0 or 3.0 to align with real world data
h2oRounding(feature_df['CH2O'])

print(Counter(feature_df['CH2O']))

Counter({2.0: 1110, 3.0: 516, 1.0: 485})

In [575]:
# Place the FCVC feature into buckets. FCVC is the question of regular fruit/veg consumption. 1 - Always, 2 - Frequently, 3 - Never
categoricalBuckets(feature_df['FCVC'])

print(Counter(feature_df['FCVC']))

Counter({'Frequently': 1013, 'Always': 996, 'Sometimes': 102})

In [576]:
# Place the NCP feature into buckets. NCP is the question of how many meals per day.

integerBuckets(feature_df['NCP'])

print(Counter(feature_df['NCP']))

Counter({0.0: 1879, 2.0: 136, 1.0: 66, 3.0: 30})

In [577]:
# Place the TUE feature into buckets. TUE is the question of how much screen time per day.

integer_3_Buckets(feature_df['TUE'])

print(Counter(feature_df['TUE']))

Counter({0.0: 1129, 1.0: 705, 2.0: 277})

In [578]:
# Place the FAF feature into buckets. FAF is the question of physical activity per day.

activityRounding(feature_df['FAF'])

print(Counter(feature_df['FAF']))

Counter({0.0: 816, 1.0: 787, 2.0: 379, 3.0: 129})

In [579]:
feature_df.rename(columns={
    'family_history_with_overweight': 'Overweight_Family_History',
    'FAVC': 'High_Caloric_Food_Frequency',
    'FCVC': 'Meal_Vegetable_Intake',
    'NCP': 'Mmain_Meals_per_Day',
    'CAEC': 'Food_Between_Meals',
    'SMOKE': 'Smoking_Status',
    'CH2O': 'Daily_Water_Intake (L)',
    'SCC': 'Monitor_Calorie_Intake',
    'FAF': 'Physical_Activity',
    'TUE': 'Screentime (hrs)',
    'CALC': 'Alcohol_Frequency',
    'MTRANS': 'Mode_of_Transportaion'},
    inplace=True)

In [580]:
feature_copy = pd.get_dummies(feature_df)

In [581]:
feature_copy.head()

,Age,Height,Weight,Overweight_Family_History,High_Caloric_Food_Frequency,Mmain_Meals_per_Day,Smoking_Status,Daily_Water_Intake (L),Monitor_Calorie_Intake,Physical_Activity,...,Food_Between_Meals_no,Alcohol_Frequency_Always,Alcohol_Frequency_Frequently,Alcohol_Frequency_Sometimes,Alcohol_Frequency_no,Mode_of_Transportaion_Automobile,Mode_of_Transportaion_Bike,Mode_of_Transportaion_Motorbike,Mode_of_Transportaion_Public_Transportation,Mode_of_Transportaion_Walking
0,21.0,1.62,64.0,1,0,0.0,0,2.0,0,0.0,...,0,0,0,0,1,0,0,0,1,0
1,21.0,1.52,56.0,1,0,0.0,1,3.0,1,3.0,...,0,0,0,1,0,0,0,0,1,0
2,23.0,1.80,77.0,1,0,0.0,0,2.0,0,2.0,...,0,0,1,0,0,0,0,0,1,0
3,27.0,1.80,87.0,0,0,0.0,0,2.0,0,2.0,...,0,0,1,0,0,0,0,0,0,1
4,22.0,1.78,89.8,0,0,0.0,0,2.0,0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [582]:
X = feature_copy.copy()

#### Final X (feature) dataframe

In [583]:
X.nunique()

Age                                              40
Height                                         1574
Weight                                         1525
Overweight_Family_History                         2
High_Caloric_Food_Frequency                       2
Mmain_Meals_per_Day                               4
Smoking_Status                                    2
Daily_Water_Intake (L)                            3
Monitor_Calorie_Intake                            2
Physical_Activity                                 4
Screentime (hrs)                                  3
BMI                                            1883
Gender_Female                                     2
Gender_Male                                       2
Meal_Vegetable_Intake_Always                      2
Meal_Vegetable_Intake_Frequently                  2
Meal_Vegetable_Intake_Sometimes                   2
Food_Between_Meals_Always                         2
Food_Between_Meals_Frequently                     2
Food_Between_Meals_Sometimes                      2
Food_Between_Meals_no                             2
Alcohol_Frequency_Always                          2
Alcohol_Frequency_Frequently                      2
Alcohol_Frequency_Sometimes                       2
Alcohol_Frequency_no                              2
Mode_of_Transportaion_Automobile                  2
Mode_of_Transportaion_Bike                        2
Mode_of_Transportaion_Motorbike                   2
Mode_of_Transportaion_Public_Transportation       2
Mode_of_Transportaion_Walking                     2
dtype: int64

In [584]:
X.head()

,Age,Height,Weight,Overweight_Family_History,High_Caloric_Food_Frequency,Mmain_Meals_per_Day,Smoking_Status,Daily_Water_Intake (L),Monitor_Calorie_Intake,Physical_Activity,...,Food_Between_Meals_no,Alcohol_Frequency_Always,Alcohol_Frequency_Frequently,Alcohol_Frequency_Sometimes,Alcohol_Frequency_no,Mode_of_Transportaion_Automobile,Mode_of_Transportaion_Bike,Mode_of_Transportaion_Motorbike,Mode_of_Transportaion_Public_Transportation,Mode_of_Transportaion_Walking
0,21.0,1.62,64.0,1,0,0.0,0,2.0,0,0.0,...,0,0,0,0,1,0,0,0,1,0
1,21.0,1.52,56.0,1,0,0.0,1,3.0,1,3.0,...,0,0,0,1,0,0,0,0,1,0
2,23.0,1.80,77.0,1,0,0.0,0,2.0,0,2.0,...,0,0,1,0,0,0,0,0,1,0
3,27.0,1.80,87.0,0,0,0.0,0,2.0,0,2.0,...,0,0,1,0,0,0,0,0,0,1
4,22.0,1.78,89.8,0,0,0.0,0,2.0,0,0.0,...,0,0,0,1,0,0,0,0,1,0

In [585]:
# Check to see if all are int/float (objective)
X.dtypes

Age                                            float64
Height                                         float64
Weight                                         float64
Overweight_Family_History                        int64
High_Caloric_Food_Frequency                      int64
Mmain_Meals_per_Day                            float64
Smoking_Status                                   int64
Daily_Water_Intake (L)                         float64
Monitor_Calorie_Intake                           int64
Physical_Activity                              float64
Screentime (hrs)                               float64
BMI                                            float64
Gender_Female                                    uint8
Gender_Male                                      uint8
Meal_Vegetable_Intake_Always                     uint8
Meal_Vegetable_Intake_Frequently                 uint8
Meal_Vegetable_Intake_Sometimes                  uint8
Food_Between_Meals_Always                        uint8
Food_Between_Meals_Frequently                    uint8
Food_Between_Meals_Sometimes                     uint8
Food_Between_Meals_no                            uint8
Alcohol_Frequency_Always                         uint8
Alcohol_Frequency_Frequently                     uint8
Alcohol_Frequency_Sometimes                      uint8
Alcohol_Frequency_no                             uint8
Mode_of_Transportaion_Automobile                 uint8
Mode_of_Transportaion_Bike                       uint8
Mode_of_Transportaion_Motorbike                  uint8
Mode_of_Transportaion_Public_Transportation      uint8
Mode_of_Transportaion_Walking                    uint8
dtype: object

## Processing target data (y)

In [586]:
# Need to Normalise the target data
y.head()

            NObeyesdad
0        Normal_Weight
1        Normal_Weight
2        Normal_Weight
3   Overweight_Level_I
4  Overweight_Level_II

#### For the purpose of buckets, I've only used 'underweight - 0', 'normal weight - 1', 'overweight - 2', 'obese - 3'

In [587]:
# Create buckets to place the target data in, and run the function

print(y['NObeyesdad'].value_counts())

# Apply function
y.apply(weightReplacement)

#Check new buckets
print(y['NObeyesdad'])

Obesity_Type_I         351
Obesity_Type_III       324
Obesity_Type_II        297
Overweight_Level_I     290
Overweight_Level_II    290
Normal_Weight          287
Insufficient_Weight    272
Name: NObeyesdad, dtype: int64
0       1
1       1
2       1
3       2
4       2
       ..
2106    3
2107    3
2108    3
2109    3
2110    3
Name: NObeyesdad, Length: 2111, dtype: object

#### Processed target data

In [588]:
y.head()

  NObeyesdad
0          1
1          1
2          1
3          2
4          2

In [589]:
y.rename(columns={'NObeyesdad': 'Obesity_Level'},
         inplace= True)

c:\Users\anups\anaconda3\envs\dev0\lib\site-packages\pandas\core\frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [590]:
y.head()

  Obesity_Level
0             1
1             1
2             1
3             2
4             2

## Processed DataFrame

In [591]:
zipped_df = pd.concat([X, y], axis= 1)
zipped_df.head()

,Age,Height,Weight,Overweight_Family_History,High_Caloric_Food_Frequency,Mmain_Meals_per_Day,Smoking_Status,Daily_Water_Intake (L),Monitor_Calorie_Intake,Physical_Activity,...,Alcohol_Frequency_Always,Alcohol_Frequency_Frequently,Alcohol_Frequency_Sometimes,Alcohol_Frequency_no,Mode_of_Transportaion_Automobile,Mode_of_Transportaion_Bike,Mode_of_Transportaion_Motorbike,Mode_of_Transportaion_Public_Transportation,Mode_of_Transportaion_Walking,Obesity_Level
0,21.0,1.62,64.0,1,0,0.0,0,2.0,0,0.0,...,0,0,0,1,0,0,0,1,0,1
1,21.0,1.52,56.0,1,0,0.0,1,3.0,1,3.0,...,0,0,1,0,0,0,0,1,0,1
2,23.0,1.80,77.0,1,0,0.0,0,2.0,0,2.0,...,0,1,0,0,0,0,0,1,0,1
3,27.0,1.80,87.0,0,0,0.0,0,2.0,0,2.0,...,0,1,0,0,0,0,0,0,1,2
4,22.0,1.78,89.8,0,0,0.0,0,2.0,0,0.0,...,0,0,1,0,0,0,0,1,0,2

In [592]:
obesity_df = zipped_df.copy()

In [593]:
obesity_df.to_csv('processed_obesity_data_YES_WEIGHT.csv')

In [594]:
obesity_df.drop(columns=['Height', 'Weight', 'BMI'], inplace = True)

In [595]:
obesity_df.to_csv('processed_obesity_data_NO_WEIGHT.csv')